pipeline:
  build:
    image: ubuntu:16.04
    commands:
      - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - apt-get update && apt-get install wget maven default-jdk google-chrome-stable -y --allow-unauthenticated
      - mvn clean test
